[package]
name = "vdd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.1", features = ["abi3", "abi3-py37"] }
driver-ipc = { path = "../../driver-ipc" }

[lints]
workspace = true
