[env]
TARGET_PATH = "debug"

[env.prod]
TARGET_PATH = "release"

[tasks.set-build-path]
env = { "BUILD_TARGET_PATH" = { script = ['''
    for /f "tokens=*" %%a in ('cargo target-dir') do set target_dir=%%a

    echo %target_dir%/%TARGET_PATH%
'''] } }

# copy all files to an output folder of artifacts
[tasks.copy]
dependencies = ["set-build-path"]
script = [
    '''
    if not exist "..\\target\\output" (
        echo Directory not found, creating it...
        mkdir ..\\target\\output
    ) else (
        echo Directory found, deleting files...
        del /S /Q /F ..\\target\\output\\*.exe
    )
    ''',
    # copy output files to it
    '''
        cp %BUILD_TARGET_PATH%/*.exe ../target/output
    ''',
]
